### ISSUE TITLE
[Bug] 'This partner doesn't appear on any sites' error message, even though the partner *does*

### ISSUE THREAD

**Issue by honor-gfsc** [geeksforsocialchange/PlaceCal#2035] opened 2023-09-04 08:31 UTC
<img width="1203" alt="Screenshot 2023-09-04 at 09 30 45" src="https://github.com/geeksforsocialchange/PlaceCal/assets/127757676/590ad18c-65ef-4c72-9dbf-c59a7d60f015">
Present on the admin page for both current partners visible on the Norwich neighbourhood site, though they are visible by going to norwich.placecal.org

**Comment by kimadactyl** [comment] 2023-10-23 16:32
Would you say this is an onboarding barrier @honor-gfsc? Is it doing it for any other ones?

**Comment by kimadactyl** [comment] 2023-10-23 16:34
Also if you can please provide full screenshots and links that would be very helpful, its hard to work from a partial screenshot like this 

Even better use the bug template :)

**Comment by honor-gfsc** [comment] 2023-10-24 12:52
Sorry, I find the bug template confusing, and full screenshots implicate privacy of users. I'm not sure how public this is. 

This appears on both current PlaceCal Norwich partners even though both are visible on norwich.placecal.org. It's a confusing and misleading error message, which could spook a user if uploading their own partner info. It has cost me time in investigating if it is telling the truth.

**Comment by katjam** [comment] 2023-10-26 09:09
> Sorry, I find the bug template confusing, and full screenshots implicate privacy of users. I'm not sure how public this is.
>

I'll escalate the task we have to improve our templates. PlaceCal will be a good repo to try using the form format with especially if we are onboarding new people over next few months. It will be a quick job to convert and fits nicely with this cycle.

**Comment by katjam** [comment] 2024-01-11 15:16
Duplicate of #2151 #1722

**Closed by katjam** 2024-01-11 15:16 UTC
