### ISSUE TITLE
[Bug]: Importer touches `calendar.updated_at`every time it is saved

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1328] opened 2022-06-17 12:53 UTC
## Description

Last updated time should only change when someone changes the calendar info. Last imported should only update when the importer runs. Possibly happening due to queue status changing?

It is currently changing constantly

## Steps to reproduce

1. View calendars

## What you expected to happen

Last updated only changes when the info is updated by a user

<img width="1215" alt="Screenshot 2022-06-17 at 13 51 55" src="https://user-images.githubusercontent.com/511734/174302062-f29a523a-6a87-40d5-8f20-3b62a915a8ed.png">

**Comment by kimadactyl** [comment] 2022-08-01 19:26
<img width="485" alt="Screenshot 2022-08-01 at 20 25 58" src="https://user-images.githubusercontent.com/511734/182229722-92f96960-fea4-40b9-9704-dad21dd8b438.png">

reopening, this seems broken again

**Comment by katjam** [comment] 2023-07-17 11:35
Closing as duplicate of #1121

**Closed by katjam** 2023-07-17 11:35 UTC
Labels: bug, patch
