### ISSUE TITLE
Add sort to datatable columns in neighbourhood admin

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#862] opened 2021-12-20 17:49 UTC

**Comment by alexandria-gfsc** [comment] 2022-01-03 12:46
This is fixed as of kim's datatables PR, right?

**Comment by katjam** [comment] 2022-01-03 13:10
Yes I am pretty sure you are right. Can you verify quickly and close?

**Comment by kimadactyl** [comment] 2022-01-03 15:08
I don't think this is done no, for me we would have a proper little advanced search area with tests, leaving this open as a "we need to tidy this up later" ticket. It's good enough for now but not exactly release quality imo.

**Comment by kimadactyl** [comment] 2022-05-11 15:08
Now a dupe of #1137

**Closed by kimadactyl** 2022-05-11 15:08 UTC
Labels: vv, eee
