### ISSUE TITLE
Update to ruby 3.x

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/PlaceCal#1707] opened 2023-02-23 09:23 UTC
Has to happen sooner or later.

**Comment by kimadactyl** [comment] 2023-02-23 10:03
Sure - but vote 'later' if it doesn't work in 20 mins!

**Comment by katjam** [comment] 2024-01-08 17:07
Closing as duplicate of #1786

**Closed by katjam** 2024-01-08 17:07 UTC
Labels: chore, needs triage
