### ISSUE TITLE
If there are no partners with that tag, it is not shown as an option in the filter list

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/PlaceCal#1909] opened 2023-05-22 13:58 UTC
## Description

Regression that has reinstated the ability to filter on categories not used by the partner - suspected cause is https://github.com/geeksforsocialchange/PlaceCal/pull/1821/files#diff-94283ee9fa75fb5564c7731d2d787c3a4046255ffeca480bfd9ab3b47d6b4167L30

**Comment by katjam** [comment] 2023-05-22 14:00
@r-ferrier Note also that the dropdown doesn't appear at all if there are no categories (I guess) - e.g. Christchurch

**Comment by ivan-kocienski-gfsc** [comment] 2023-05-22 16:02
Not sure if this is so much as a regression or that we haven't updated our original tagging code to deal with the new fancy typed tagging system

**Comment by r-ferrier** [comment] 2023-05-22 16:06
We think this is a problem caused by having two different types of filtering on this page. 

The categories listed in the dropdown are set by this, which has access to the full list of partners:

```
  def categories
    @categories ||= Category
                    .joins(:partner_tags)
                    .group('tags.id')
                    .having('count(tag_id) > 0')
                    .order(:name)
  end
```

The partners available in the page however are limited by a `:for_site` scope which strips some of them out if they don't meet these location criteria:

```
  query
        .left_joins(:address, :service_areas)
        .where(
          '(service_areas.neighbourhood_id in (:neighbourhood_ids) OR addresses.neighbourhood_id in (:neighbourhood_ids))',
          neighbourhood_ids: site_neighbourhood_ids
        )
        .distinct
```

Because the two sets have a different set of partners to choose from, sometimes the categories dropdown thinks there are partners available for some categories when the page content does not

**Comment by r-ferrier** [comment] 2023-05-22 16:09
I think this used to work @ivan-kocienski-gfsc because it used to also take into consideration the `@partners` variable from the partner controller, maybe if that can be passed into the partner category filter it can be applied in the same way? I'm just not sure how it was working before and why it doesn't now 😅

**Comment by katjam** [comment] 2023-05-22 16:58
Have you proven with a git bisect that you are looking at the right commit?

**Comment by r-ferrier** [comment] 2023-05-25 10:27
Alas, broken in a different way now. Have checked this with a copy of the prod DB locally and it looks like categories are just hidden for everyone now.

Production:
![Screenshot 2023-05-25 at 11 26 08](https://github.com/geeksforsocialchange/PlaceCal/assets/46496391/0448e9d4-21d1-42e7-844e-85ebc394c20f)

local:
![Screenshot 2023-05-25 at 11 26 13](https://github.com/geeksforsocialchange/PlaceCal/assets/46496391/f005d391-35a6-4faf-bdd7-f73018166bac)

**Comment by katjam** [comment] 2023-05-29 08:26
This was reopened due to https://github.com/geeksforsocialchange/PlaceCal/issues/1917. Closing again since the work to fix is being done there, but will need verifying once that is also released.

**Comment by katjam** [comment] 2023-05-29 08:27
This was reopened due to https://github.com/geeksforsocialchange/PlaceCal/issues/1917. Closing again since the work to fix is being done there, but will need verifying once that is also released.

**Closed by katjam** 2023-05-29 08:27 UTC
Labels: bug, dependencies
