### ISSUE TITLE
[Bug]: Navigation isn't showing up

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1545] opened 2022-11-11 16:33 UTC
## Description

Browsing PlaceCal on my mac, the navigation is invisible

## Steps to reproduce

1. Open up https://gmsc.placecal.org/
1. Open up https://placecal.org/
1. On both there is no navigation

<img width="1321" alt="Screenshot 2022-11-11 at 16 32 24" src="https://user-images.githubusercontent.com/511734/201386552-29c33234-1f03-413e-acfa-b3f3be498254.png">

<img width="1423" alt="Screenshot 2022-11-11 at 16 32 29" src="https://user-images.githubusercontent.com/511734/201386573-5c841335-ba7f-4c5c-8234-76e3b250495c.png">

## Platform (if relevant)

Mac OS 13.0 (M1)
Firefox 106.0.1 (64 Bit)

**Comment by erbridge** [comment] 2022-11-11 20:40
Can't reproduce on macOS 12.6 (M1), Firefox 107.0b9. Were you on a flaky internet connection at the time?

**Comment by kimadactyl** [comment] 2022-11-11 20:50
No, and it's still happening. Really weird huh?

**Comment by erbridge** [comment] 2022-11-11 21:02
Does it happen in a private browsing session without extensions installed?

**Comment by kimadactyl** [comment] 2022-11-14 11:37
Good catch. The suspect is... Firefox's built in Facebook Container? Eh?

**Comment by erbridge** [comment] 2022-11-14 14:57
Because we used to have gross Facebook integrations?

**Comment by ivan-kocienski-gfsc** [comment] 2022-11-14 15:51
so this is not a bug then?

**Comment by kimadactyl** [comment] 2022-11-14 16:09
It's also doing it not in a Facebook container. If I disable the plugin it works immediately. It came as stock installed for me and is on both my laptop and desktop. 

<img width="1008" alt="Screenshot 2022-11-14 at 16 07 52" src="https://user-images.githubusercontent.com/511734/201708426-da635b24-f871-449f-843e-1a684043f655.png">

<img width="695" alt="Screenshot 2022-11-14 at 16 07 45" src="https://user-images.githubusercontent.com/511734/201708503-79d9a7cd-27ed-40c2-917c-3585bab8f15c.png">

**Comment by aaaaargZombies** [comment] 2022-11-14 16:42
I installed the plugin but couldn't reproduce the bug

**Comment by ivan-kocienski-gfsc** [comment] 2024-01-09 15:48
@honor-gfsc just checked this on their mac on firefox and it works, so closing

<img width="1392" alt="Screenshot_2024-01-09_at_15 44 58" src="https://github.com/geeksforsocialchange/PlaceCal/assets/109223824/8980e522-5d09-4d1e-b9bb-94811d2f1e01">
<img width="1392" alt="Screenshot_2024-01-09_at_15 45 24" src="https://github.com/geeksforsocialchange/PlaceCal/assets/109223824/f586b9c7-0d65-4804-b2ed-cf75d70e07e8">

**Closed by ivan-kocienski-gfsc** 2024-01-09 15:48 UTC
Labels: bug, needs triage
