### ISSUE TITLE
[Bug]: Counties do not display when choosing Neighbourhood information 

### ISSUE THREAD

**Issue by honor-gfsc** [geeksforsocialchange/PlaceCal#2380] opened 2024-04-10 10:00 UTC
## Description

When choosing a Neighbourhood either for a neighbourhood_admin or a site, counties are missing from the list of options. This means one has to manually add each District within a County to effectively grant the same permissions. 

## What you expected to happen

~~- [ ] Counties (or all neighbourhoods?) should be choosable from the list of site neighbourhoods~~
~~- [ ] Counties (or all neighbourhoods?) should be choosable from the list of user neighbourhoods~~

- [ ] Admin dropdowns show name not abbreviated name fields
- [ ] Improve neighbourhood admin text if this isn't good enough as is

**Comment by aaaaargZombies** [comment] 2024-04-12 10:25
> As noted at standup today this is hopefully an `e` fix and is just missing options from the dropdown.
> 
> If not then this is prob an `eee`. Boo!

oh boy - wish the reasons for this had been added to the ticket  - wish me luck

**Comment by aaaaargZombies** [comment] 2024-04-12 10:54
Struggling to reproduce this bug as a `root`

![2024-04-12-11:51:39-screenshot](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/eab18006-44e1-4f0d-9fde-fa6285c7f664)
![2024-04-12-11:51:56-screenshot](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/6937492d-18b9-4ab6-a808-1ac4a10d3836)
![2024-04-12-11:52:04-screenshot](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/7f4666bd-cad4-4f1a-b0b8-361639a7cb44)

Will move on to other types of admin - Good case for adding the "how to reproduce" section to a bug report.

**Comment by aaaaargZombies** [comment] 2024-04-12 12:03
Created a `partnership_admin` and `site_admin` for tran dimension manchester, `neighbourhood_admin` for england

- only `root` users can add new neighborhoods to sites I believe so not applicable.
- again I don't have permission to assign neighbourhoods to users when not a `root`.

I can still access counties when setting the service area for partners.

![2024-04-12-12:59:14-screenshot](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/93eba070-8d5e-4242-9379-8592e4bcdfd1)

**Comment by katjam** [comment] 2024-04-12 13:37
From memory of dealing with this in Manchester, it was that the area that people talk about being defined as "Greater Manchester" is not recognised as an area by our neighbourhood chooser. This may be to do with the fact that it's a ceremonial county https://en.wikipedia.org/wiki/Ceremonial_counties_of_England

So if there is a "bug" it could be that ceremonial counties are not included but that we could pull them in with a different set of parameters?

I think this was also agreed as not a priority for this milestone because there is an acceptable work-around that involves selecting on a more granular level, specifically the areas you want. In some ways having options that encompass larger areas, will encourage people to claim areas they are not actually active in.

**Comment by aaaaargZombies** [comment] 2024-04-15 10:54
Disccusion with devs today and it looks like there's a couple of things going on

- on the ground interpretations of where county borders are differs between people and from the dataset.
- Greater Manchester **is** a county but was given a nickname which made it hard to find. 

![2024-04-15-11:33:37-screenshot](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/cd0c0fc3-bbed-4584-bad4-d2fbac8bd3cd)

![2024-04-15-11:32:46-screenshot](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/a4361458-f002-4042-bc4f-da9bf52f351b)


I will open an issue to discuss if we should get rid of nicknames as this could be useful for the person who names it but misleading for everyone else.

**Comment by kimadactyl** [comment] 2024-04-15 11:05
Omg that makes so much sense. It was put in as some of the neighbourhood names can get absurdly long and this breaks the public interface. The idea of it is that neighbourhood admins can set a shorter term for public view, we prob need to intergrate this into the training @honor-gfsc. This isn't even the longest one I've seen but gives you an idea how silly it gets.

<img width="516" alt="Screenshot 2024-04-15 at 12 03 12" src="https://github.com/geeksforsocialchange/PlaceCal/assets/511734/5e298507-3028-496d-82bf-30bf9e8f24b6">

Propose that we just change the admin dropdowns to show the regular name field and not the nickname one, and optionally add a bit of UI text to this effect in the neighbourhood admin?

**Comment by kimadactyl** [comment] 2024-04-15 11:09
Ah - update - this isn't it for me either - I can't see `Gtr Mcr` or `Greater Manchester` on the public placecal?

<img width="1107" alt="Screenshot 2024-04-15 at 12 09 13" src="https://github.com/geeksforsocialchange/PlaceCal/assets/511734/a4b48c4a-140a-4203-952a-d93c31b09f3c">
<img width="1085" alt="Screenshot 2024-04-15 at 12 09 25" src="https://github.com/geeksforsocialchange/PlaceCal/assets/511734/1dc9cb90-b339-4979-831d-4aaed001addf">

**Comment by kimadactyl** [comment] 2024-04-15 11:11
Hang on I'm confusing myself now - it is working - are you sure about the abbreviation thing? Disregard my messages I'm going a bit fast. @honor-gfsc is your ward showing up or no?

**Comment by aaaaargZombies** [comment] 2024-04-15 11:14
closing as won't fix, combination of user error and labeling that didn't give users the best chance of success.

Abbreviation has now been ticketed here for further discussion about user friendliness #2393

**Closed by aaaaargZombies** 2024-04-15 11:15 UTC
Labels: won't fix
