### ISSUE TITLE
London Trans+ Meetup import not working due to location or place not found

### ISSUE THREAD

**Issue by ivankocienski** [geeksforsocialchange/PlaceCal#1202] opened 2022-05-02 13:33 UTC
On [staging](https://admin.placecal-staging.org/calendars/96) calendar edit page, the following Important Notices are reported:

The following events could not be imported due to invalid data:

    7 Apr 2022. Drab Drink London. No place or address could be created or found for the event location: Retro Bar, 2 George Court, London, England, WC2N 6HH
    5 May 2022. London Trans+ Meet Up Dashboard. No place or address could be created or found for the event location: Retro Bar, 2 George Court, London, England, WC2N 6HH
    2 Jun 2022. London Trans+ Meet Up Dashboard. No place or address could be created or found for the event location: Retro Bar, 2 George Court, London, England, WC2N 6HH 

Context: Drab Drink London (production: calendar ID 96) 

It would appear to not be resolving the address correctly in the importer

**Comment by kimadactyl** [comment] 2022-05-02 14:06
OK this is a dupe of #1201 i think!

**Closed** 2022-05-03 16:40 UTC
