### ISSUE TITLE
Making a new user in the localhost testing environment gives 500 "No route matches [GET] "/users""

### ISSUE THREAD

**Issue by alexandria-gfsc** [geeksforsocialchange/PlaceCal#807] opened 2021-12-02 16:05 UTC
Flow:
- http://admin.lvh.me:3000/users -> Add New User
- Submit, get the localhost signup page (Incorrectly redirects to localhost rather than lvh.me:3000 - maybe root cause)
- Click on the link in the signup page, get the error

**Comment by kimadactyl** [comment] 2022-06-15 19:07
Duplicate of another issue which is now resolved

**Closed by kimadactyl** 2022-06-15 19:07 UTC
