### ISSUE TITLE
Allow editor of partner to set service area

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/PlaceCal#1721] opened 2023-03-02 14:01 UTC
## Acceptance Criteria

- [ ] A partner must have at least an address and one or more service areas
- [ ] Anyone who can edit a partner can set its service area
- [ ] It is clear to the partner admin that the service area is "where their services are accessed" in most zoomed in level

## Description

When logged in as User 147 (i believe?) and visiting https://admin.placecal.org/partners/oshun-abi-dougill/edit the service area selector has no service areas

## Notes

If a admin User has no Neighbourhoods then when they go to edit a Partner the Service Area selector is empty. When I think what we want is- if the logged in User is on a Partner they own then they can set any Neighbourhood.

## Implementation Notes

So if a logged in admin is viewing a partner that they own, they can set service areas regardless of their neighbourhoods

**Comment by kimadactyl** [comment] 2023-03-02 15:20
I think we should let people set service areas if they can edit a partner. How it is now presumably means partners can't edit their own service areas either - doens't really make sense to me.

https://gfsc.notion.site/Partnership-Admins-57027fb4d8a644e091f3a0ac70e17e0b

**Comment by katjam** [comment] 2023-03-02 15:36
I believe this immediate problem has been resolved by giving the user a neighbourhood. To futureproof for exactly this situate, the simplest thing to do would be inform the partner that they need to be assigned a neighbourhood in order to use the system.

**Comment by kimadactyl** [comment] 2023-03-02 15:38
The problem is she can see and edit all 200 or so partners in Manchester now - this seems bad and I think makes the system somewhat unusable? It's not "breaking" in the bug sense but it feels high prio to fix for me

**Comment by kimadactyl** [comment] 2023-03-02 15:39
Also like I say - presumably partners can't currently set their own service areas

**Comment by katjam** [comment] 2023-03-02 15:39
> The problem is she can see and edit all 200 or so partners in Manchester now - this seems bad and I think makes the system somewhat unusable? It's not "breaking" in the bug sense but it feels high prio to fix for me

Ah OK, so you still feel like it it is critical?

**Comment by kimadactyl** [comment] 2023-03-02 15:40
Yes - i feel pretty strongly that partnerships should only have to worry about their own partners and not interact with everything out there. Feels like a recipe for disaster esp as we don't have any kind of admin logging if people start doing silly things.

**Comment by ivan-kocienski-gfsc** [comment] 2023-03-03 11:17
It might also be worth putting in some feedback on this issue explaining that people who cannot assign anything to this partner can't make that selection at all (sorry for the bad wording)

**Comment by kimadactyl** [comment] 2023-03-06 17:49
Confirmed partners can't set their own service areas - got some more asks about this today, this ticket is prob highest prio when we get back on it

**Comment by katjam** [comment] 2023-03-15 16:57
@ivan-kocienski-gfsc will add implementation notes around watching out for service area related permissions

**Comment by r-ferrier** [comment] 2023-04-27 11:28
I Had a look at this but the last comment on it says @ivan-kocienski-gfsc has some implementation notes to add - could you add these for us Ivan?

**Comment by kimadactyl** [comment] 2023-05-02 11:42
Hey this keeps getting deprioritised and im not sure why - this is a critical bug that's stopping whole categories of our current users from editing things. It's marked `vvv` / `ee` also - I am not sure why we have these designations if they're not being used to priortise tickets!

Moving to top - I think this is the biggest outstanding user bug.

**Comment by katjam** [comment] 2023-05-02 11:46
Sorry my fault on the priority. I thought we'd decided that we didn't want to do anything that those top ones flagged as urgent in here - to focus on the homepage. I think it was blocked before because we were waiting for Ivan to comment which was done in the main description, but not flagged. All good to be worked on now, I think!

**Comment by kimadactyl** [comment] 2023-05-02 11:57
yeah - its ok. i think the labels aren't really working for us tho, i see urgent was removed from it but im not sure why.

we prob need to do a little bit of a rethink here - having labels, milestone order, milestones themselves, vvv/eee labels etc to priortise things with no real guide to what each means is causing a lot of confusion. maybe need a bit of a rethink how we do this?

**Comment by katjam** [comment] 2023-05-02 13:51
If I remember, we removed that urgent when we kicked off the dev work on 15 March because we decided it wasn't any longer urgent... but not sure who was there for that meeting.

**Comment by kimadactyl** [comment] 2023-05-02 13:58
Yeah I mean it's really urgent and also far more urgent than other stuff that has been done like say, fixing the URL params for the filter. I think we need some better mechaisms for prioritising than just who happens to be at a given meeting. Maybe some kind of "what is a critical ticket?" checklist?

**Comment by katjam** [comment] 2023-05-02 14:57
It's probably not fair to pre-populate the retro but I'll add this to the list so we don't forget.

**Comment by ivan-kocienski-gfsc** [comment] 2023-05-03 22:45
okay i think i need a clarification: if i am an admin who has a neighbourhood and i am editing a partner that has that neighbourhood (as a service area) then i can see all the neighbourhoods that this partner has been assigned (but i can only assign my own neighbourhood)? but what about removing neighbourhoods? i can only remove my neighbourhood?

**Closed** 2023-05-09 16:38 UTC
Labels: vvv, ee, impacts client

**Comment by katjam** [comment] 2023-05-24 13:38
![image](https://github.com/geeksforsocialchange/PlaceCal/assets/861172/379f79b1-c51a-4e08-a758-158e0a2771ef)
