### ISSUE TITLE
Refactor unusual jQuery import

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/PlaceCal#1388] opened 2022-07-19 10:07 UTC
## User story

As a developer I need jQuery to behave consistently so that I can use depend on it when I write features.

## Acceptance criteria

- [ ] Remove need for `app/javascript/src/jquery.js`

## Implementation notes & questions

Will the current tests wrote by Ivan break if I remove jQuery? If so I can use this to confirm it's fixed.

jQuery is currently added to global namespace like this.

```
import jquery from "jquery"
window.jQuery = jquery
window.$ = jquery
```
This seems to have resulted in libraries like select2 needing additional binding that isn't covered in the libraries documentation.

```
require("select2")(window, $)
```

## Implementation plan

1. Read current jQuery docs and implement what they suggest.
2. Troubleshoot if needed.

**Comment by kimadactyl** [comment] 2022-07-19 10:18
I think the `app/javascript/src/jquery.js` is how you're supposed to do it. It's all the other stuff that is the problem (maybe?)

**Comment by kimadactyl** [comment] 2022-07-19 10:19
@pedantic-git if you have any insight here I'm all ears. We just can't get jquery to play nicely with stimulus. It looks like you ripped it all out in name.pn?

**Comment by kimadactyl** [comment] 2022-07-19 10:25
Would you reccomend we try and deprecate all our jQuery depends rather than fight with it?

**Comment by pedantic-git** [comment] 2022-07-19 10:27
I think as long as you don't mix jquery and stimulus together it should be OK - like don't use any jquery dependencies inside your stimulus controllers (and bundle all your jquery legacy code with sprockets) but I haven't looked at this specific issue in detail - I can do when I'm at my FP desk tomorrow

**Comment by kimadactyl** [comment] 2022-07-19 10:46
Yeah the big kicker atm is that the browser "back" button seems to break everything, lol. This is part of a big messy ticket that's us starting to refactor the lot.

Maybe we should just skip this and try and deprecate JQuery afterall @aaaaargZombies?

**Comment by aaaaargZombies** [comment] 2022-07-19 10:59
hmm I'd be interested in @pedantic-git's opinion on #1387.

My thought's were that a stimulus controller that just attaches the jQuery plugin to the correct DOM elements as they load in would be OK but having not tried it it's quite likely I'm missing something.

**Comment by pedantic-git** [comment] 2022-07-19 11:18
The browser back button issue is more likely to be being caused by turbolinks, or some interaction between turbolinks and jquery. From my jquery days I remember I had to add a lot of unregistering of handlers before reregistering them in order to get it to play nicely with turbolinks. That's something that's solved in stimulus because it picks up where to attach the handlers from the DOM itself (whereas jquery you set them all globally in your JS code)

**Comment by pedantic-git** [comment] 2022-07-20 08:44
@aaaaargZombies Sorry for missing your message. Select2 being still dependent on jQuery is annoying but thankfully you're not the only person to be annoyed by it! I've had great success in several Stimulus projects switching away from Select2 to https://github.com/orchidjs/tom-select which is a jquery-less fork of selectize (so it doesn't have quite the same API as Select2 but it does have all the same features and isn't always that painful to switch to). Honestly I couldn't rave more about tom-select!

**Comment by aaaaargZombies** [comment] 2022-07-20 08:49
No problem, everything you've said already has been helpful. Though it's very nice to get this detailed response. ☺️

**Comment by pedantic-git** [comment] 2022-07-20 08:51
Always happy to help however I can!

**Comment by kimadactyl** [comment] 2022-08-01 15:55
OK closing this as wontfix for now as this is probably going to be cleaned up indirectly now the Great Migration has begun. We can reopen if more stench detected

**Closed** 2022-08-01 15:55 UTC
Labels: ee, patch, enhancement, chore
