### ISSUE TITLE
[Bug]: Partner address should only be required if the partner does not have at least one service area

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#1914] opened 2023-05-24 14:04 UTC
## Description

Trying to add a service area and remove an address.

This might be relevant to note: https://github.com/geeksforsocialchange/PlaceCal/issues/1219

## Steps to reproduce

1. On a partner that has an address saved,
1. Add a service area
2. remove the address fields
3. the address persists & also does not let you save if one of the "required" fields is not filled in

## What you expected to happen

- [ ] If a partner has at least one service area, they do not need an address
- [ ] If I delete an existing partner address, I should be able to save the partner

## Platform (if relevant)

What device and browser were you using?

**Comment by kimadactyl** [comment] 2023-05-24 14:29
Just to repeat what i put in discord, the issue is this line:

https://github.com/geeksforsocialchange/PlaceCal/blob/main/app/models/partner.rb#L90

If an address is created, then blanked out, it needs to delete the address record, not try and validate it.

Line 95 looks like it's working correctly for the rest of it so this should be a quick fix.

**Comment by ivan-kocienski-gfsc** [comment] 2023-05-25 15:38
The problem is that when the record is created and address params are present then AR will automatically create that address record and populate the fields and validate. But if the values are missing it doesn't do this so no address will be created and no validation will occur.

but if a partner has an address removing those fields won't delete the address record as it assumes the blank fields are new values, which in turn updates the address and therefor runs the validation and that fails.

if the params are missing from an update request then AR leaves the address as is (and doesn't run the validation).

So what we want is something like "if the address fields are blank or missing from the update action then delete the address" logic. 

Or some kind of button like "remove the address" to do it literally

**Comment by r-ferrier** [comment] 2024-01-17 12:28
closing this as it describes the same problem as https://github.com/geeksforsocialchange/PlaceCal/issues/1219, and is linked to from there

**Closed by r-ferrier** 2024-01-17 12:28 UTC
Labels: bug, requires research, duplicate
