### ISSUE TITLE
Work out what to do about skip levels in the neighbourhood hierarchy

### ISSUE THREAD

**Issue by erbridge** [geeksforsocialchange/PlaceCal#1477] opened 2022-10-05 16:28 UTC
## Details

Not every Ward -> Country hierarchy has all 5 layers in it. Right now we have a `(not set)` label for those gaps, but that's a bit gnarly and tightly couples us to the UK's nonsense.

My reckon is that it's better to draw a direct line from root to leaf nodes in the tree and label them appropriately. It's possible we already do that but hide it in how we show them in the UI.

We need to work this out because we're planning on making it possible to drill down through the hierarchy to find the neighbourhood in your area and we need to know how we're going to represent the skips.

## Acceptance criteria

- [ ] We have one or more issues with more specific work

**Comment by kimadactyl** [comment] 2022-10-05 17:10
To me this is not a bug. It means that the heirarchy is very consistently organised and you can navigate up and down it without having to be unclear what you are accessing. My instinct is to fix this at the UI end not the database end?

This is not strongly held though. I just think you might find some assumptions in the codebase on this one.

**Comment by katjam** [comment] 2024-01-11 12:38
Has been fixed by new neighbourhood system.

**Closed by katjam** 2024-01-11 12:38 UTC
Labels: won't fix, design
