### ISSUE TITLE
[Bug]: malformed links on area homepages for wifi and computer access

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/PlaceCal#1452] opened 2022-09-13 13:30 UTC
## Description

when looking for computer or wifi access I try to visit a partner but get taken to a list of all partners.

## Steps to reproduce

1. Vist https://hulme.placecal.org/
1. Under the "computer access"  section click on "Hulme High Street Library"

## What you expected to happen

you will be taken to https://hulme.placecal.org/places.hulme-high-street-library instead of https://hulme.placecal.org/partners/hulme-high-street-library

## Suspected cause

https://github.com/geeksforsocialchange/PlaceCal/blob/0a4bf5f2fee0dd6f2b0809a85ff8e7e05f7bd55d/app/components/free_public_wifi/_free_public_wifi.html.erb#L27
https://github.com/geeksforsocialchange/PlaceCal/blob/0a4bf5f2fee0dd6f2b0809a85ff8e7e05f7bd55d/app/components/computer_access/_computer_access.html.erb#L23

I couldn't see where the method `places_url` was defined.

**Comment by kimadactyl** [comment] 2022-09-13 14:18
Dupe of  #1443

**Comment by kimadactyl** [comment] 2022-09-13 14:23
Sorry I misread!

**Closed** 2022-09-15 09:14 UTC
Labels: bug, patch
